[build]
  command = "npm run build"
  publish = "dist"
  functions = "api"

[functions]
  node_bundler = "esbuild"

# If your app posts to /auth-login, route it to the function:
[[redirects]]
  from = "/auth-login"
  to = "/.netlify/functions/auth-login"
  status = 200
  force = true

# If you also use /api/* anywhere, keep this:
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
